services:
  amneziawgml:
    image: metaligh/amneziawg:latest
    container_name: amnezia_container
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
#    volumes:
#      - /opt/amneziawg:/etc/amnezia:rw
    ports:
      - "51820:51820/udp"
    restart: unless-stopped
