version: '3'

services:
  db:
    image: mariadb:10.5
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - ${APP_DATA_DIR}/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${APP_DB_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${APP_DB_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud:27.1.3
    restart: always
    ports:
      - "9090:80"
    links:
      - db
    volumes:
      - ${APP_DATA_DIR}/nextcloud:/var/www/html
      - ${APP_DATA_DIR}/apps:/var/www/html/custom_apps
      - ${APP_DATA_DIR}/config:/var/www/html/config
      - ${APP_DATA_DIR}/data:/var/www/html/data
    environment:
      - NEXTCLOUD_DATA_DIR=/var/www/html/data
      - MYSQL_PASSWORD=${APP_DB_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - NEXTCLOUD_ADMIN_USER=${APP_NEXTCLOUD_ADMIN}
      - NEXTCLOUD_ADMIN_PASSWORD=${APP_NEXTCLOUD_PASSWORD}
      - NEXTCLOUD_TRUSTED_DOMAINS=${APP_DOMAIN} localhost
      - TZ=Europe/Moscow

volumes:
  nextcloud:
  db:
